services:
  frontend:
    build: .
    container_name: haivler_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
